// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/myapp/noname/api/application/usecase"
	"github.com/myapp/noname/api/infrastructure/db"
	"github.com/myapp/noname/api/infrastructure/repository"
	"github.com/myapp/noname/api/infrastructure/response"
	"github.com/myapp/noname/api/presentation/v1/handler"
)

// Injectors from wire.go:

func InitBeautician() handler.Beautician {
	conn := db.New()
	beautician := repository.NewBeautician(conn)
	responseBeautician := response.NewBeautician()
	menu := repository.NewMenu(conn)
	salon := repository.NewSalon(conn)
	usecaseBeautician := usecase.NewBeautician(beautician, responseBeautician, menu, salon)
	handlerBeautician := handler.NewBeautician(usecaseBeautician)
	return handlerBeautician
}

func InitReservation() handler.Reservation {
	conn := db.New()
	guest := repository.NewGuest(conn)
	reservation := repository.NewReservation(conn)
	responseReservation := response.NewReservation()
	beautician := repository.NewBeautician(conn)
	usecaseReservation := usecase.NewReservation(guest, reservation, responseReservation, beautician)
	handlerReservation := handler.NewReservation(usecaseReservation)
	return handlerReservation
}

func InitSalon() handler.Salon {
	conn := db.New()
	salon := repository.NewSalon(conn)
	responseSalon := response.NewSalon()
	beautician := repository.NewBeautician(conn)
	usecaseSalon := usecase.NewSalon(salon, responseSalon, beautician)
	handlerSalon := handler.NewSalon(usecaseSalon)
	return handlerSalon
}

func InitMenu() handler.Menu {
	conn := db.New()
	menu := repository.NewMenu(conn)
	responseMenu := response.NewMenu()
	beautician := repository.NewBeautician(conn)
	usecaseMenu := usecase.NewMenu(menu, responseMenu, beautician)
	handlerMenu := handler.NewMenu(usecaseMenu)
	return handlerMenu
}
