// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/myapp/noname/api/application/usecase"
	"github.com/myapp/noname/api/presentation/v1/handler"
)

// Injectors from wire.go:

func InitTest() handler.Test {
	test := usecase.NewTest()
	handlerTest := handler.NewTest(test)
	return handlerTest
}
