// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	BeauticianMenus  string
	BeauticianSalons string
	Beauticians      string
	Guests           string
	Menus            string
	Reservation      string
	Salons           string
	Spaces           string
}{
	BeauticianMenus:  "beautician_menus",
	BeauticianSalons: "beautician_salons",
	Beauticians:      "beauticians",
	Guests:           "guests",
	Menus:            "menus",
	Reservation:      "reservation",
	Salons:           "salons",
	Spaces:           "spaces",
}
