// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Beauticians string
	Guests      string
	Menus       string
	Stores      string
}{
	Beauticians: "beauticians",
	Guests:      "guests",
	Menus:       "menus",
	Stores:      "stores",
}
