// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testGuests(t *testing.T) {
	t.Parallel()

	query := Guests()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testGuestsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGuestsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Guests().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGuestsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GuestSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGuestsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := GuestExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Guest exists: %s", err)
	}
	if !e {
		t.Errorf("Expected GuestExists to return true, but got false.")
	}
}

func testGuestsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	guestFound, err := FindGuest(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if guestFound == nil {
		t.Error("want a record, got nil")
	}
}

func testGuestsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Guests().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testGuestsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Guests().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testGuestsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	guestOne := &Guest{}
	guestTwo := &Guest{}
	if err = randomize.Struct(seed, guestOne, guestDBTypes, false, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}
	if err = randomize.Struct(seed, guestTwo, guestDBTypes, false, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = guestOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = guestTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Guests().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testGuestsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	guestOne := &Guest{}
	guestTwo := &Guest{}
	if err = randomize.Struct(seed, guestOne, guestDBTypes, false, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}
	if err = randomize.Struct(seed, guestTwo, guestDBTypes, false, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = guestOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = guestTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func guestBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func guestAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Guest) error {
	*o = Guest{}
	return nil
}

func testGuestsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Guest{}
	o := &Guest{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, guestDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Guest object: %s", err)
	}

	AddGuestHook(boil.BeforeInsertHook, guestBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	guestBeforeInsertHooks = []GuestHook{}

	AddGuestHook(boil.AfterInsertHook, guestAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	guestAfterInsertHooks = []GuestHook{}

	AddGuestHook(boil.AfterSelectHook, guestAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	guestAfterSelectHooks = []GuestHook{}

	AddGuestHook(boil.BeforeUpdateHook, guestBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	guestBeforeUpdateHooks = []GuestHook{}

	AddGuestHook(boil.AfterUpdateHook, guestAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	guestAfterUpdateHooks = []GuestHook{}

	AddGuestHook(boil.BeforeDeleteHook, guestBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	guestBeforeDeleteHooks = []GuestHook{}

	AddGuestHook(boil.AfterDeleteHook, guestAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	guestAfterDeleteHooks = []GuestHook{}

	AddGuestHook(boil.BeforeUpsertHook, guestBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	guestBeforeUpsertHooks = []GuestHook{}

	AddGuestHook(boil.AfterUpsertHook, guestAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	guestAfterUpsertHooks = []GuestHook{}
}

func testGuestsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGuestsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(guestColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGuestToManyReservations(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b, c Reservation

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, reservationDBTypes, false, reservationColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, reservationDBTypes, false, reservationColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.GuestID = a.ID
	c.GuestID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Reservations().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.GuestID == b.GuestID {
			bFound = true
		}
		if v.GuestID == c.GuestID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := GuestSlice{&a}
	if err = a.L.LoadReservations(ctx, tx, false, (*[]*Guest)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Reservations); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Reservations = nil
	if err = a.L.LoadReservations(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Reservations); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testGuestToManyAddOpReservations(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Guest
	var b, c, d, e Reservation

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, guestDBTypes, false, strmangle.SetComplement(guestPrimaryKeyColumns, guestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Reservation{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, reservationDBTypes, false, strmangle.SetComplement(reservationPrimaryKeyColumns, reservationColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Reservation{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddReservations(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.GuestID {
			t.Error("foreign key was wrong value", a.ID, first.GuestID)
		}
		if a.ID != second.GuestID {
			t.Error("foreign key was wrong value", a.ID, second.GuestID)
		}

		if first.R.Guest != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Guest != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Reservations[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Reservations[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Reservations().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testGuestsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGuestsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GuestSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGuestsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Guests().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	guestDBTypes = map[string]string{`ID`: `bigint`, `AuthID`: `varchar`, `RandID`: `varchar`, `FirstName`: `varchar`, `LastName`: `varchar`, `FirstNameKana`: `varchar`, `LastNameKana`: `varchar`, `Email`: `varchar`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`, `DeletedAt`: `datetime`}
	_            = bytes.MinRead
)

func testGuestsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(guestPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(guestAllColumns) == len(guestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, guestDBTypes, true, guestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testGuestsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(guestAllColumns) == len(guestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Guest{}
	if err = randomize.Struct(seed, o, guestDBTypes, true, guestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, guestDBTypes, true, guestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(guestAllColumns, guestPrimaryKeyColumns) {
		fields = guestAllColumns
	} else {
		fields = strmangle.SetComplement(
			guestAllColumns,
			guestPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := GuestSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testGuestsUpsert(t *testing.T) {
	t.Parallel()

	if len(guestAllColumns) == len(guestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLGuestUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Guest{}
	if err = randomize.Struct(seed, &o, guestDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Guest: %s", err)
	}

	count, err := Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, guestDBTypes, false, guestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Guest struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Guest: %s", err)
	}

	count, err = Guests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
