// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("BeauticianMenus", testBeauticianMenusUpsert)

	t.Run("BeauticianSalons", testBeauticianSalonsUpsert)

	t.Run("Beauticians", testBeauticiansUpsert)

	t.Run("Guests", testGuestsUpsert)

	t.Run("Menus", testMenusUpsert)

	t.Run("Reservations", testReservationsUpsert)

	t.Run("Salons", testSalonsUpsert)

	t.Run("Spaces", testSpacesUpsert)
}
