// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSalons(t *testing.T) {
	t.Parallel()

	query := Salons()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSalonsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Salons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSalonsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Salons().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Salons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSalonsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SalonSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Salons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSalonsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SalonExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Salon exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SalonExists to return true, but got false.")
	}
}

func testSalonsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	salonFound, err := FindSalon(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if salonFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSalonsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Salons().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSalonsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Salons().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSalonsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	salonOne := &Salon{}
	salonTwo := &Salon{}
	if err = randomize.Struct(seed, salonOne, salonDBTypes, false, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}
	if err = randomize.Struct(seed, salonTwo, salonDBTypes, false, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = salonOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = salonTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Salons().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSalonsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	salonOne := &Salon{}
	salonTwo := &Salon{}
	if err = randomize.Struct(seed, salonOne, salonDBTypes, false, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}
	if err = randomize.Struct(seed, salonTwo, salonDBTypes, false, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = salonOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = salonTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Salons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func salonBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Salon) error {
	*o = Salon{}
	return nil
}

func salonAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Salon) error {
	*o = Salon{}
	return nil
}

func salonAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Salon) error {
	*o = Salon{}
	return nil
}

func salonBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Salon) error {
	*o = Salon{}
	return nil
}

func salonAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Salon) error {
	*o = Salon{}
	return nil
}

func salonBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Salon) error {
	*o = Salon{}
	return nil
}

func salonAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Salon) error {
	*o = Salon{}
	return nil
}

func salonBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Salon) error {
	*o = Salon{}
	return nil
}

func salonAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Salon) error {
	*o = Salon{}
	return nil
}

func testSalonsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Salon{}
	o := &Salon{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, salonDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Salon object: %s", err)
	}

	AddSalonHook(boil.BeforeInsertHook, salonBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	salonBeforeInsertHooks = []SalonHook{}

	AddSalonHook(boil.AfterInsertHook, salonAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	salonAfterInsertHooks = []SalonHook{}

	AddSalonHook(boil.AfterSelectHook, salonAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	salonAfterSelectHooks = []SalonHook{}

	AddSalonHook(boil.BeforeUpdateHook, salonBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	salonBeforeUpdateHooks = []SalonHook{}

	AddSalonHook(boil.AfterUpdateHook, salonAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	salonAfterUpdateHooks = []SalonHook{}

	AddSalonHook(boil.BeforeDeleteHook, salonBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	salonBeforeDeleteHooks = []SalonHook{}

	AddSalonHook(boil.AfterDeleteHook, salonAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	salonAfterDeleteHooks = []SalonHook{}

	AddSalonHook(boil.BeforeUpsertHook, salonBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	salonBeforeUpsertHooks = []SalonHook{}

	AddSalonHook(boil.AfterUpsertHook, salonAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	salonAfterUpsertHooks = []SalonHook{}
}

func testSalonsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Salons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSalonsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(salonColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Salons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSalonToManySpaces(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Salon
	var b, c Space

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, spaceDBTypes, false, spaceColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, spaceDBTypes, false, spaceColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.SalonID = a.ID
	c.SalonID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Spaces().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.SalonID == b.SalonID {
			bFound = true
		}
		if v.SalonID == c.SalonID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := SalonSlice{&a}
	if err = a.L.LoadSpaces(ctx, tx, false, (*[]*Salon)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Spaces); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Spaces = nil
	if err = a.L.LoadSpaces(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Spaces); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testSalonToManyAddOpSpaces(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Salon
	var b, c, d, e Space

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, salonDBTypes, false, strmangle.SetComplement(salonPrimaryKeyColumns, salonColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Space{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, spaceDBTypes, false, strmangle.SetComplement(spacePrimaryKeyColumns, spaceColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Space{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddSpaces(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.SalonID {
			t.Error("foreign key was wrong value", a.ID, first.SalonID)
		}
		if a.ID != second.SalonID {
			t.Error("foreign key was wrong value", a.ID, second.SalonID)
		}

		if first.R.Salon != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Salon != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Spaces[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Spaces[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Spaces().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testSalonsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSalonsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SalonSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSalonsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Salons().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	salonDBTypes = map[string]string{`ID`: `bigint`, `RandID`: `varchar`, `Name`: `varchar`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`, `DeletedAt`: `datetime`}
	_            = bytes.MinRead
)

func testSalonsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(salonPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(salonAllColumns) == len(salonPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Salons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, salonDBTypes, true, salonPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSalonsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(salonAllColumns) == len(salonPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Salon{}
	if err = randomize.Struct(seed, o, salonDBTypes, true, salonColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Salons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, salonDBTypes, true, salonPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(salonAllColumns, salonPrimaryKeyColumns) {
		fields = salonAllColumns
	} else {
		fields = strmangle.SetComplement(
			salonAllColumns,
			salonPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SalonSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSalonsUpsert(t *testing.T) {
	t.Parallel()

	if len(salonAllColumns) == len(salonPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLSalonUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Salon{}
	if err = randomize.Struct(seed, &o, salonDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Salon: %s", err)
	}

	count, err := Salons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, salonDBTypes, false, salonPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Salon struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Salon: %s", err)
	}

	count, err = Salons().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
