steps:
- id: "test"
  name: 'golang'
  env: ['GO111MODULE=on']
  args: ['go', 'test', './...']
  dir: './api'

- id: 'build'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cutmatch-docker-repo/cutmatch-api-image:tag1',
          '--build-arg', '_CLOUD_SQL_CONNECTION_PASS=$_CLOUD_SQL_CONNECTION_PASS', '--build-arg', '_CLOUD_SQL_CONNECTION_NAME=$_CLOUD_SQL_CONNECTION_NAME', '.' ]
  dir: './api'

- id: 'cloudsql-proxy'
  name: 'gcr.io/cloudsql-docker/gce-proxy:1.15'
  entrypoint: 'sh'
  args: ['-c', '/cloud_sql_proxy -dir=/cloudsql -instances=$_CLOUD_SQL_CONNECTION_NAME & while [ ! -f /cloudsql/stop ]; do sleep 2; done']
  volumes: 
    - name: cloudsql
      path: /cloudsql
  waitFor:
    - 'test'
  dir: './api'

- id: 'migration'
  name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', 'cloudsql:/cloudsql', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cutmatch-docker-repo/cutmatch-api-image:tag1', 'make', 'cloudbuild-cloudsql']
  volumes:
    - name: cloudsql
      path: /cloudsql
  waitFor:
    - 'build'
  dir: './api'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: ['-c', 'touch /cloudsql/stop']
  volumes:
    - name: cloudsql
      path: /cloudsql
  waitFor:
      - 'migration'
  dir: './api'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cutmatch-docker-repo/cutmatch-api-image:tag1']
  dir: './api'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cutmatch-api', '--image', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cutmatch-docker-repo/cutmatch-api-image:tag1', '--region', 'asia-northeast1', '--platform', 'managed']
  dir: './api'

images:
- 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cutmatch-docker-repo/cutmatch-api-image:tag1'

substitutions:
  _CLOUD_SQL_CONNECTION_NAME: ''
  _CLOUD_SQL_CONNECTION_PASS: ''