runtime: nodejs12
instance_class: F1

handlers:
  - url: /static
    static_dir: build/static
  - url: /(.*\.(json|ico|js|svg|png))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|svg|png)$
  - url: .*
    static_files: build/index.html
    upload: build/index.html
    expiration: '0s'